import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Link
            href="/productOrders"
            className="m-3 underline hover:text-blue-500"
          >
            All Product Orders
          </Link>
          <Link
            href="/productOrders/create"
            className="underline hover:text-blue-500"
          >
            Create Product Order
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
